### ISSUE TITLE
BINANCE_API_KEY

### ISSUE THREAD

**Issue by Wasif-Maqsood** [nMaroulis/sibyl#1]
Hi,
Hope you are doing good.
You do a wonderfull project I really apprciate it.

I have a error in these lines.

BINANCE_API_KEY = get_api_key("binance")[0]  # change to binance
BINANCE_API_SECRET_KEY = get_api_key("binance")[1]

I have binance api key and secret key when I add it in backend/setting.py I encounter a problem in the file when i add [0], to it get_api_key("binance"). Without it It execute sucessfully but in front there is empty credentials . and when I click on forecasting ,new error comes
File "/home/wise/AI-Projects/sibyl/frontend/pages/00_Forecasting.py", line 36, in <module>
    exchange_api = exchange_api.replace(' ', '_').lower()
   
Can you please tell me where I am doing the mistake 
Thanks
I shall to very thankfull to you for this favour.

**Comment by nMaroulis** [comment]
Hi Wasif, thanks for your nice comment and sorry for the late reply. I would suggest to create a file called api_credentials.json in the backend/config/api_keys directory. Please see the api_credentials_template.py in the same directory and follow its structure. By creating this file the rest will work :).
